name: Generate Samba RPM Package

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches: ["main"]
    
    tags:
      - rpm*
      - all*


env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: generate_samba_rpm

jobs:
  # Run tests.
  prepare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run tests
        run: |
          if ! [ -f Dockerfile ]; then
            docker 
          fi
    
  build:
    needs: prepare

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M%S')"
        
      - name: Build CentOS Package
        id: build_package
        run: |
          sudo apt-get install rpm
          . build/version

          mkdir opt
          tar -zxvf samba_source/samba-centos*.tar.gz
          mkdir -p opt/samba4/usr/lib/systemd/system/
          cp etc/systemd/system/samba4.service opt/samba4/usr/lib/systemd/system/
          ls -al /

          rpmbuildroot=$(pwd)/build
          echo "%_topdir            $rpmbuildroot/rpmbuild" > ~/.rpmmacros
          mkdir -p $rpmbuildroot/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
          cp -r src/usr/* opt/samba4/usr/
          cp -r opt/samba4/* $rpmbuildroot/rpmbuild/BUILD
          
          build_number="${{ github.run_number }}"
          echo """Name: sambahvl
          Version: $ver
          Release: $build_number
          Summary: Kurumsal Samba Paketi
          License: GPLv2
          Packager: Fatih Arslan Tugay
          Requires: iniparser libldb libtalloc libtdb libtevent gnutls-devel libacl-devel openldap-devel pam-devel readline-devel krb5-devel cups-devel epel-release python3-devel lmdb-devel lmdb gpgme-devel jansson-devel libarchive-devel python3 krb5-workstation python3-dns krb5-workstation avahi-libs avahi-libs oddjob oddjob-mkhomedir

          %description
          Kurumsal ihtiyaclara gore derlenmis samba paketi

          %install
          mkdir -p %{buildroot}
          cp -ra * %{buildroot}/

          %post
          kill -TERM 1
          chmod +x /usr/local/bin/smb*
          ln -s /usr/local/bin/* /usr/bin/
          systemctl stop sssd
          systemctl disable sssd

          %files""" > $rpmbuildroot/rpmbuild/SPECS/sambahvl.spec
          find ./opt/samba4/  -type f,l  | sort  | sed "s+.*opt/samba4++g" | grep -v "\/man\/"  >> $rpmbuildroot/rpmbuild/SPECS/sambahvl.spec
          find ./opt/samba4/ -depth -empty -type d | sed "s+.*opt/samba4++g" >> $rpmbuildroot/rpmbuild/SPECS/sambahvl.spec
          echo "%define _unpackaged_files_terminate_build 0" >> $rpmbuildroot/rpmbuild/SPECS/sambahvl.spec

          rpmbuild -ba  $rpmbuildroot/rpmbuild/SPECS/sambahvl.spec
          rpmpath=$(find $rpmbuildroot/rpmbuild/RPMS/ -type f)
          echo ::set-output name=path::$rpmpath
          echo ::set-output name=filename::$(echo $rpmpath | sed "s/.*\///")
          echo ::set-output name=version::"$ver"

      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release.rpm.${{steps.build_package.outputs.version}}-${{ github.run_number }}
          release_name: "Release: rpm ${{steps.build_package.outputs.version}}-${{ github.run_number }}"
          body: |
            Changes in this Release
            - Will be add.
          draft: false
          prerelease: false

      - name: Upload the CentOS package to Release Assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.build_package.outputs.path }}
          asset_name: ${{ steps.build_package.outputs.filename }}
          asset_content_type: application/vnd.debian.binary-package
